# Generated by Django 4.2.1 on 2023-05-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_backend', '0002_todo_description_alter_todo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
