# Generated by Django 4.2.1 on 2023-05-30 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_backend', '0004_todo_date_alter_todo_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='date',
            new_name='dueDate',
        ),
    ]
