# Generated by Django 4.2.1 on 2023-05-30 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_backend', '0005_rename_date_todo_duedate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='dueDate',
            new_name='date',
        ),
    ]
